export const areasOfInterests = Object.freeze([
  'Artificial Intelligence (AI) and Machine Learning (ML)',
  'Data Science and Big Data',
  'Computer Vision and Image Processing',
  'Distributed Systems and Cloud Computing',
  'Networks and Cybersecurity',
  'Software Engineering and Development',
  'Human-Computer Interaction (HCI)',
  'Computer Graphics and Visualization',
  'Natural Computing and Quantum Computing',
  'Bioinformatics and Computational Biology',
  'Internet of Things (IoT)',
  'Robotics and Autonomous Systems',
  'Quantum Computing',
  'Ethics in Computing',
  'Education and E-Learning',
  'Natural Language Processing (NLP)',
  'Social Computing and Social Networks',
  'Core Systems',
]);
